services:
  db:
    image: postgres:latest
    container_name: completionist_db_compose
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testPassword
      POSTGRES_DB: completionist_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - completionist-net

networks:
  completionist-net:
    driver: bridge

volumes:
  postgres_data:
