import json
import os
import re
import sys

SWAGGER_FILE = os.path.join("swagger", "swagger.json")
OUTPUT_FILE = "completionist_api.postman_collection.json"
BASE_URL = "http://localhost:8080/api"

WORKFLOW_DEFINITIONS = [
    {
        "step_name": "1. Register New User",
        "path": "/register",
        "method": "POST",
        "body_override": {
            "username": "AutoUser_{{$timestamp}}",
            "email": "auto_{{$timestamp}}@test.com",
            "password": "password123"
        },
        "event": [
            {
                "listen": "test",
                "script": {
                    "exec": [
                        "pm.test('Status is 201', function () { pm.response.to.have.status(201); });",
                        "// Save credentials for the next step",
                        "var req = JSON.parse(pm.request.body.raw);",
                        "pm.collectionVariables.set('current_email', req.email);",
                        "pm.collectionVariables.set('current_password', req.password);"
                    ],
                    "type": "text/javascript"
                }
            }
        ]
    },
    {
        "step_name": "2. Login",
        "path": "/login",
        "method": "POST",
        "body_override": {
            "email": "{{current_email}}",
            "password": "{{current_password}}"
        },
        "event": [
            {
                "listen": "test",
                "script": {
                    "exec": [
                        "pm.test('Status is 200', function () { pm.response.to.have.status(200); });",
                        "var jsonData = pm.response.json();",
                        "// Automatically set the Bearer Token for all future requests",
                        "pm.collectionVariables.set('token', jsonData.token);",
                        "console.log('Token set:', jsonData.token);"
                    ],
                    "type": "text/javascript"
                }
            }
        ]
    },
    {
        "step_name": "3. Get My Profile",
        "path": "/me",
        "method": "GET",
        "event": [
            {
                "listen": "test",
                "script": {
                    "exec": [
                        "pm.test('Status is 200', function () { pm.response.to.have.status(200); });",
                        "var jsonData = pm.response.json();",
                        "pm.test('Username matches', function () {",
                        "    var email = pm.collectionVariables.get('current_email');",
                        "    pm.expect(jsonData.email).to.eql(email);",
                        "});"
                    ],
                    "type": "text/javascript"
                }
            }
        ]
    },
    {
        "step_name": "4. Create a Post",
        "path": "/posts",
        "method": "POST",
        "body_override": {
            "title": "Automated Post {{$timestamp}}",
            "content": "This is a test post generated by the automated workflow.",
            "postType": "general",
            "isSpoiler": False,
            "rating": 5
        },
        "event": [
            {
                "listen": "test",
                "script": {
                    "exec": [
                        "pm.test('Status is 201', function () { pm.response.to.have.status(201); });",
                        "var jsonData = pm.response.json();",
                        "// Capture the ID so we can delete/edit it later",
                        "pm.collectionVariables.set('created_post_id', jsonData.id);"
                    ],
                    "type": "text/javascript"
                }
            }
        ]
    },
    {
        "step_name": "5. Add Comment to Post",
        "path": "/posts/{post_id}/comments",
        "method": "POST",
        "path_vars_override": {
            "post_id": "{{created_post_id}}"
        },
        "body_override": {
            "content": "This is an automated comment."
        },
        "event": [
            {
                "listen": "test",
                "script": {
                    "exec": [
                        "pm.test('Status is 201', function () { pm.response.to.have.status(201); });"
                    ],
                    "type": "text/javascript"
                }
            }
        ]
    },
    {
        "step_name": "6. Clean Up (Delete Post)",
        "path": "/posts/{post_id}",
        "method": "DELETE",
        "path_vars_override": {
            "post_id": "{{created_post_id}}"
        },
        "event": [
            {
                "listen": "test",
                "script": {
                    "exec": [
                        "pm.test('Status is 204', function () { pm.response.to.have.status(204); });"
                    ],
                    "type": "text/javascript"
                }
            }
        ]
    }
]

def load_swagger():
    if not os.path.exists(SWAGGER_FILE):
        print(f"Error: {SWAGGER_FILE} not found. Run 'swag init' first.")
        sys.exit(1)
    with open(SWAGGER_FILE, 'r') as f:
        return json.load(f)

def convert_url(path):
    return re.sub(r'\{(.*?)\}', r':\1', path)

def create_item(name, method, url_path, body=None, description="", headers=None, events=None, path_vars=None):
    postman_path = convert_url(url_path)
    
    item = {
        "name": name,
        "request": {
            "method": method.upper(),
            "header": headers if headers else [{"key": "Content-Type", "value": "application/json"}],
            "url": {
                "raw": "{{baseUrl}}" + postman_path,
                "host": ["{{baseUrl}}"],
                "path": postman_path.strip("/").split("/"),
                "variable": []
            }
        }
    }

    if description:
        item["request"]["description"] = description

    if events:
        item["event"] = events

    if ":" in postman_path:
        vars_in_path = re.findall(r':([a-zA-Z0-9_]+)', postman_path)
        for var in vars_in_path:
            val = ""
            if path_vars and var in path_vars:
                val = path_vars[var]
            
            item["request"]["url"]["variable"].append({
                "key": var,
                "value": val
            })

    if body:
        item["request"]["body"] = {
            "mode": "raw",
            "raw": json.dumps(body, indent=2)
        }

    return item

def generate_reference_folders(swagger):
    folders = {}
    for path, methods in swagger.get("paths", {}).items():
        for method, details in methods.items():
            tags = details.get("tags", ["Uncategorized"])
            folder_name = tags[0]

            if folder_name not in folders:
                folders[folder_name] = {"name": f"{folder_name}", "item": []}

            example_body = {}
            if "parameters" in details:
                for param in details["parameters"]:
                    if param.get("in") == "body":
                        schema = param.get("schema", {})
                        ref = schema.get("$ref", "")
                        if ref:
                            def_name = ref.split("/")[-1]
                            definition = swagger.get("definitions", {}).get(def_name, {})
                            for prop_name, prop_val in definition.get("properties", {}).items():
                                prop_type = prop_val.get("type", "string")
                                example_body[prop_name] = 0 if prop_type == "integer" else "string"

            item = create_item(
                name=details.get("summary", f"{method.upper()} {path}"),
                method=method,
                url_path=path,
                body=example_body if example_body else None,
                description=details.get("description", "")
            )
            folders[folder_name]["item"].append(item)
    
    return [folders[name] for name in sorted(folders.keys())]

def generate_workflow_folder():
    workflow_items = []
    for step in WORKFLOW_DEFINITIONS:
        item = create_item(
            name=step["step_name"],
            method=step["method"],
            url_path=step["path"],
            body=step.get("body_override"),
            events=step.get("event"),
            path_vars=step.get("path_vars_override")
        )
        workflow_items.append(item)
    
    return {
        "name": "Integration Test Workflow",
        "description": "Automatically created sequence to test User Creation, Login, and Data creation.",
        "item": workflow_items
    }

def main():
    print("Generating Postman Collection with Automated Workflow...")
    swagger = load_swagger()
    
    collection = {
        "info": {
            "name": "Completionist API (Dev)",
            "description": "Auto-generated collection with Test Workflow",
            "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
        },
        "variable": [
            {"key": "baseUrl", "value": BASE_URL, "type": "string"},
            {"key": "token", "value": "", "type": "string"},
            {"key": "current_email", "value": "", "type": "string"},
            {"key": "current_password", "value": "", "type": "string"},
            {"key": "created_post_id", "value": "", "type": "string"}
        ],
        "auth": {
            "type": "bearer",
            "bearer": [{"key": "token", "value": "{{token}}", "type": "string"}]
        },
        "item": []
    }

    collection["item"].append(generate_workflow_folder())

    reference_folders = generate_reference_folders(swagger)
    collection["item"].extend(reference_folders)
    
    with open(OUTPUT_FILE, 'w') as f:
        json.dump(collection, f, indent=2)
    
    print(f"Success! Postman collection saved to: {os.path.abspath(OUTPUT_FILE)}")

if __name__ == "__main__":
    main()